### ISSUE TITLE
是否考虑兼容 class 类写法呢？

### ISSUE THREAD

**Issue by proc07** [1340641314/flex.css#16]
微信小程序不支持 [flex] 这种写法
example: 
```css
.flex{
  display: flex
}
```
